### PR TITLE
Fix for nllb

### LINKED ISSUE #63: [BUG]: nllb200_distilled_600M official not running properly
I'm using nllb200_distilled_600M official model (using cache, not offine downloaded)
running following programs:
``` python
import dl_translate as dlt
import nltk
nltk.data.path.append(r"E:\xxx\nltk_data")

mt = dlt.TranslationModel("nllb200")
mt = dlt.TranslationModel("facebook/nllb-200-distilled-600M")

text = "This paper presents a literature survey on existing disparity map algorithms. It focuses on four main stages of processing as proposed by Scharstein and Szeliski in a taxonomy and evaluation of dense two-frame stereo correspondence algorithms performed in 2002. To assist future researchers in developing their own stereo matching algorithms, a summary of the existing algorithms developed for every stage of processing is also provided. The survey also notes the implementation of previous software-based and hardware-based algorithms. Generally, the main processing module for a software-based implementation uses only a central processing unit. By contrast, a hardware-based implementation requires one or more additional processors for its processing module, such as graphical processing unit or a field programmable gate array. This literature survey also presents a method of qualitative measurement that is widely used by researchers in the area of stereo vision disparity mappings. "
sents = nltk.tokenize.sent_tokenize(text, "english")
print("".join(mt.translate(sents, source="eng_Latn", target="zho_Hans")))
```

Bugs occur:
``` shell
$  File "E:\xxx\translation.py", line 16, in <module>
$    print("".join(mt.translate(sents, source=dlt.lang.ENGLISH, target="zho_Hans")))
$  File "E:\xxx\Anaconda3\envs\DLTranslation\lib\site-packages\dl_translate\_translation_model.py", line 173, in translate
$    "forced_bos_token_id", self._tokenizer.lang_code_to_id[target]
$ AttributeError: 'NllbTokenizerFast' object has no attribute 'lang_code_to_id'
```

But when i using other model like m2m100, there is no problem, really need help!!!

### PR DESCRIPTION
**Pull request by Galoist**
Fixes #63

### CODE REVIEW

**Comment by xhluca** [comment]
Will merge once the tests pass!

**Review by xhluca — APPROVED** [review]

**Review by xhluca — CHANGES_REQUESTED** [review]
Would it be possible to change the minimum version for this in the setup.py, so users with older versions before the function was added can upgrade their version of transformers?

**Comment by xhluca** [comment]
Right now it is `transformers>=4.30.2` but i'm uncertain if that feature existed in 4.30

**Comment by Galoist** [comment]
It seems to work with transformers==4.30.2

pixi.toml:
```
[project]
authors = ["..."]
channels = ["conda-forge"]
description = "Add a short description here"
name = "translate"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.11"
ipython = ">=8.27.0,<9"

[pypi-dependencies]
dl-translate = { git = "https://github.com/Galoist/dl-translate" }
transformers = "==4.30.2"
```

```
In [1]: import dl_translate as dlt
   ...:

In [2]: translate_model: str = "facebook/nllb-200-distilled-600M"

In [3]:         mt = dlt.TranslationModel(translate_model, device="mps")
/private/tmp/translate/.pixi/envs/default/lib/python3.11/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/private/tmp/translate/.pixi/envs/default/lib/python3.11/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/private/tmp/translate/.pixi/envs/default/lib/python3.11/site-packages/transformers/modeling_utils.py:463: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(checkpoint_file, map_location="cpu")

In [4]: mt.translate("Привіт, світ!", dlt.lang.nllb200.UKRAINIAN, dlt.lang.nllb200.FRENCH)
Out[4]: 'Je vous salue, mon ami.'
```

**Comment by xhluca** [comment]
Awesome! In that case, i'll merge now
